<?php

namespace App\Support;

/**
 * The location pool for spy rounds, ported from the original SPA's
 * src/data/locations.ts. Ids are renumbered in file order (the SPA reuses 51
 * and 52) and are what game_rounds stores, so never renumber or reorder
 * existing entries: append new ones with the next id.
 *
 * Tiers are cumulative: a teens game draws from children + teens, an adults
 * game from everything (see AgeTier::includedTiers()).
 */
class LocationData
{
    /**
     * @var array<string, array{en: string, uk: string}>
     */
    public const CATEGORIES = [
        'historical' => ['en' => 'Historical & Sacred', 'uk' => 'Історичні та сакральні місця'],
        'academic' => ['en' => 'Academic & Civic', 'uk' => 'Освіта та державні установи'],
        'transit' => ['en' => 'Transit & Aviation', 'uk' => 'Транспорт і авіація'],
        'hospitality' => ['en' => 'Hospitality & Dining', 'uk' => 'Гостинність і ресторани'],
        'entertainment' => ['en' => 'Entertainment & Arts', 'uk' => 'Розваги та мистецтво'],
        'sports' => ['en' => 'Sports & Athletics', 'uk' => 'Спорт і тренування'],
        'commercial' => ['en' => 'Commercial & Retail', 'uk' => 'Торгівля та ринки'],
        'industry' => ['en' => 'Industry & Infrastructure', 'uk' => 'Промисловість та інфраструктура'],
        'medical' => ['en' => 'Medical & Emergency', 'uk' => 'Медицина та безпека'],
        'espionage' => ['en' => 'Espionage & Covert', 'uk' => 'Шпигунство та таємні локації'],
    ];

    /**
     * @var list<array{id: int, en: string, uk: string, category: string, tier: string}>
     */
    public const PLACES = [
        ['id' => 1, 'en' => 'Church', 'uk' => 'Церква', 'category' => 'historical', 'tier' => 'children'],
        ['id' => 2, 'en' => 'Palace', 'uk' => 'Палац', 'category' => 'historical', 'tier' => 'children'],
        ['id' => 3, 'en' => 'Castle', 'uk' => 'Замок', 'category' => 'historical', 'tier' => 'children'],
        ['id' => 4, 'en' => 'Windsor Castle', 'uk' => 'Віндзорський замок', 'category' => 'historical', 'tier' => 'children'],
        ['id' => 5, 'en' => 'Buckingham Palace', 'uk' => 'Букінгемський палац', 'category' => 'historical', 'tier' => 'children'],
        ['id' => 6, 'en' => 'Cathedral', 'uk' => 'Собор', 'category' => 'historical', 'tier' => 'children'],
        ['id' => 7, 'en' => 'Monastery', 'uk' => 'Монастир', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 8, 'en' => 'Ancient Temple', 'uk' => 'Стародавній храм', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 9, 'en' => 'Mosque', 'uk' => 'Мечеть', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 10, 'en' => 'Synagogue', 'uk' => 'Синагога', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 11, 'en' => 'Shrine', 'uk' => 'Святилище', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 12, 'en' => 'Pyramid', 'uk' => 'Піраміда', 'category' => 'historical', 'tier' => 'children'],
        ['id' => 13, 'en' => 'Medieval Fortress', 'uk' => 'Середньовічна фортеця', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 14, 'en' => 'Royal Abbey', 'uk' => 'Королівське абатство', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 15, 'en' => 'Citadel', 'uk' => 'Цитадель', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 16, 'en' => 'Crypt', 'uk' => 'Крипта', 'category' => 'historical', 'tier' => 'adults'],
        ['id' => 17, 'en' => 'Catacombs', 'uk' => 'Катакомби', 'category' => 'historical', 'tier' => 'adults'],
        ['id' => 18, 'en' => 'Mausoleum', 'uk' => 'Мавзолей', 'category' => 'historical', 'tier' => 'adults'],
        ['id' => 19, 'en' => 'Ancient Ruins', 'uk' => 'Стародавні руїни', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 20, 'en' => 'Royal Gardens', 'uk' => 'Королівські сади', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 21, 'en' => 'Clock Tower', 'uk' => 'Годинникова вежа', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 22, 'en' => 'Bell Tower', 'uk' => 'Дзвіниця', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 23, 'en' => 'Manor House', 'uk' => 'Панський маєток', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 24, 'en' => 'Chateau', 'uk' => 'Шато', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 25, 'en' => 'Grand Bastion', 'uk' => 'Великий бастіон', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 26, 'en' => 'Keep', 'uk' => 'Донжон', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 27, 'en' => 'Stonehenge', 'uk' => 'Стоунгендж', 'category' => 'historical', 'tier' => 'children'],
        ['id' => 28, 'en' => 'Amphitheater', 'uk' => 'Амфітеатр', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 29, 'en' => 'Colosseum', 'uk' => 'Колізей', 'category' => 'historical', 'tier' => 'children'],
        ['id' => 30, 'en' => 'Acropolis', 'uk' => 'Акрополь', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 31, 'en' => 'Pantheon', 'uk' => 'Пантеон', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 32, 'en' => 'Pagoda', 'uk' => 'Пагода', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 33, 'en' => 'Zen Temple', 'uk' => 'Дзен-храм', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 34, 'en' => 'Papal Residence', 'uk' => 'Папська резиденція', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 35, 'en' => 'Knights Hall', 'uk' => 'Лицарська зала', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 36, 'en' => 'Dungeon', 'uk' => 'Підземелля замку', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 37, 'en' => 'Royal Treasury', 'uk' => 'Королівська скарбниця', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 38, 'en' => 'Coronation Chamber', 'uk' => 'Коронаційна палата', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 39, 'en' => 'Throne Room', 'uk' => 'Тронна зала', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 40, 'en' => 'Armory', 'uk' => 'Збройова палата', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 41, 'en' => 'Great Wall Outpost', 'uk' => 'Застава Великого муру', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 42, 'en' => 'Windmill', 'uk' => 'Вітряк', 'category' => 'historical', 'tier' => 'children'],
        ['id' => 43, 'en' => 'Watermill', 'uk' => 'Водяний млин', 'category' => 'historical', 'tier' => 'children'],
        ['id' => 44, 'en' => 'Lighthouse', 'uk' => 'Маяк', 'category' => 'historical', 'tier' => 'children'],
        ['id' => 45, 'en' => 'Historic Mill', 'uk' => 'Історичний млин', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 46, 'en' => 'Old Granary', 'uk' => 'Старий амбар', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 47, 'en' => 'Baroque Ballroom', 'uk' => 'Барокова бальна зала', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 48, 'en' => 'Gothic Chapel', 'uk' => 'Готична каплиця', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 49, 'en' => 'Renaissance Courtyard', 'uk' => 'Ренесансний двір', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 50, 'en' => 'Ancient Agora', 'uk' => 'Стародавня агора', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 51, 'en' => 'Roman Baths', 'uk' => 'Римські терми', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 52, 'en' => 'Viking Longhouse', 'uk' => 'Довгий будинок вікінгів', 'category' => 'historical', 'tier' => 'teens'],
        ['id' => 53, 'en' => 'School', 'uk' => 'Школа', 'category' => 'academic', 'tier' => 'children'],
        ['id' => 54, 'en' => 'High School', 'uk' => 'Старша школа', 'category' => 'academic', 'tier' => 'children'],
        ['id' => 55, 'en' => 'University Campus', 'uk' => 'Університетське містечко', 'category' => 'academic', 'tier' => 'teens'],
        ['id' => 56, 'en' => 'Elementary School', 'uk' => 'Початкова школа', 'category' => 'academic', 'tier' => 'children'],
        ['id' => 57, 'en' => 'Kindergarten', 'uk' => 'Дитсадок', 'category' => 'academic', 'tier' => 'children'],
        ['id' => 58, 'en' => 'Boarding School', 'uk' => 'Школа-інтернат', 'category' => 'academic', 'tier' => 'teens'],
        ['id' => 59, 'en' => 'Public Library', 'uk' => 'Публічна бібліотека', 'category' => 'academic', 'tier' => 'children'],
        ['id' => 60, 'en' => 'National Archives', 'uk' => 'Національний архів', 'category' => 'academic', 'tier' => 'teens'],
        ['id' => 61, 'en' => 'Art Museum', 'uk' => 'Художній музей', 'category' => 'academic', 'tier' => 'children'],
        ['id' => 62, 'en' => 'Natural History Museum', 'uk' => 'Музей природничої історії', 'category' => 'academic', 'tier' => 'children'],
        ['id' => 63, 'en' => 'Modern Art Gallery', 'uk' => 'Галерея сучасного мистецтва', 'category' => 'academic', 'tier' => 'teens'],
        ['id' => 64, 'en' => 'Science Center', 'uk' => 'Науковий центр', 'category' => 'academic', 'tier' => 'children'],
        ['id' => 65, 'en' => 'Planetarium', 'uk' => 'Планетарій', 'category' => 'academic', 'tier' => 'children'],
        ['id' => 66, 'en' => 'Observatory', 'uk' => 'Астрономічна обсерваторія', 'category' => 'academic', 'tier' => 'teens'],
        ['id' => 67, 'en' => 'Botanical Garden', 'uk' => 'Ботанічний сад', 'category' => 'academic', 'tier' => 'children'],
        ['id' => 68, 'en' => 'City Hall', 'uk' => 'Ратуша (Міська рада)', 'category' => 'academic', 'tier' => 'children'],
        ['id' => 69, 'en' => 'Courthouse', 'uk' => 'Будівля суду', 'category' => 'academic', 'tier' => 'adults'],
        ['id' => 70, 'en' => 'Supreme Court', 'uk' => 'Верховний суд', 'category' => 'academic', 'tier' => 'adults'],
        ['id' => 71, 'en' => 'Parliament House', 'uk' => 'Будівля парламенту', 'category' => 'academic', 'tier' => 'adults'],
        ['id' => 72, 'en' => 'Capitol Building', 'uk' => 'Будівля капітолію', 'category' => 'academic', 'tier' => 'adults'],
        ['id' => 73, 'en' => 'Embassy', 'uk' => 'Посольство', 'category' => 'academic', 'tier' => 'adults'],
        ['id' => 74, 'en' => 'Consulate', 'uk' => 'Консульство', 'category' => 'academic', 'tier' => 'adults'],
        ['id' => 75, 'en' => 'United Nations Assembly', 'uk' => 'Генеральна Асамблея ООН', 'category' => 'academic', 'tier' => 'adults'],
        ['id' => 76, 'en' => 'Mayor\'s Office', 'uk' => 'Кабінет мера', 'category' => 'academic', 'tier' => 'teens'],
        ['id' => 77, 'en' => 'Police Station', 'uk' => 'Поліцейський відділок', 'category' => 'academic', 'tier' => 'children'],
        ['id' => 78, 'en' => 'Fire Station', 'uk' => 'Пожежна частина', 'category' => 'academic', 'tier' => 'children'],
        ['id' => 79, 'en' => 'Post Office', 'uk' => 'Поштове відділення', 'category' => 'academic', 'tier' => 'children'],
        ['id' => 80, 'en' => 'Customs House', 'uk' => 'Митниця', 'category' => 'academic', 'tier' => 'adults'],
        ['id' => 81, 'en' => 'Immigration Bureau', 'uk' => 'Імміграційне бюро', 'category' => 'academic', 'tier' => 'adults'],
        ['id' => 82, 'en' => 'Central Bank', 'uk' => 'Центральний банк', 'category' => 'academic', 'tier' => 'adults'],
        ['id' => 83, 'en' => 'Stock Exchange', 'uk' => 'Фондова біржа', 'category' => 'academic', 'tier' => 'adults'],
        ['id' => 84, 'en' => 'Treasury Mint', 'uk' => 'Монетний двір', 'category' => 'academic', 'tier' => 'adults'],
        ['id' => 85, 'en' => 'Military Academy', 'uk' => 'Військова академія', 'category' => 'academic', 'tier' => 'teens'],
        ['id' => 86, 'en' => 'Naval College', 'uk' => 'Військово-морський коледж', 'category' => 'academic', 'tier' => 'teens'],
        ['id' => 87, 'en' => 'Flight School', 'uk' => 'Льотна школа', 'category' => 'academic', 'tier' => 'teens'],
        ['id' => 88, 'en' => 'Culinary Institute', 'uk' => 'Кулінарний інститут', 'category' => 'academic', 'tier' => 'teens'],
        ['id' => 89, 'en' => 'Ballet Academy', 'uk' => 'Балетна академія', 'category' => 'academic', 'tier' => 'teens'],
        ['id' => 90, 'en' => 'Conservatory of Music', 'uk' => 'Музична консерваторія', 'category' => 'academic', 'tier' => 'teens'],
        ['id' => 91, 'en' => 'Lecture Hall', 'uk' => 'Лекційна аудиторія', 'category' => 'academic', 'tier' => 'teens'],
        ['id' => 92, 'en' => 'University Laboratory', 'uk' => 'Університетська лабораторія', 'category' => 'academic', 'tier' => 'teens'],
        ['id' => 93, 'en' => 'Student Dormitory', 'uk' => 'Студентський гуртожиток', 'category' => 'academic', 'tier' => 'teens'],
        ['id' => 94, 'en' => 'Campus Quad', 'uk' => 'Кампусний двір', 'category' => 'academic', 'tier' => 'teens'],
        ['id' => 95, 'en' => 'Alumni Hall', 'uk' => 'Зала випускників', 'category' => 'academic', 'tier' => 'teens'],
        ['id' => 96, 'en' => 'Examination Center', 'uk' => 'Екзаменаційний центр', 'category' => 'academic', 'tier' => 'teens'],
        ['id' => 97, 'en' => 'Community Center', 'uk' => 'Громадський центр', 'category' => 'academic', 'tier' => 'teens'],
        ['id' => 98, 'en' => 'Civic Auditorium', 'uk' => 'Міська концертна зала', 'category' => 'academic', 'tier' => 'teens'],
        ['id' => 99, 'en' => 'Town Square', 'uk' => 'Міська площа', 'category' => 'academic', 'tier' => 'teens'],
        ['id' => 100, 'en' => 'Historical Society', 'uk' => 'Історичне товариство', 'category' => 'academic', 'tier' => 'teens'],
        ['id' => 101, 'en' => 'Patent Office', 'uk' => 'Патентне бюро', 'category' => 'academic', 'tier' => 'adults'],
        ['id' => 102, 'en' => 'Meteorological Institute', 'uk' => 'Метеорологічний інститут', 'category' => 'academic', 'tier' => 'teens'],
        ['id' => 103, 'en' => 'Airport Terminal', 'uk' => 'Термінал аеропорту', 'category' => 'transit', 'tier' => 'children'],
        ['id' => 104, 'en' => 'Control Tower', 'uk' => 'Диспетчерська вежа', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 105, 'en' => 'Airplane Cabin', 'uk' => 'Салон пасажирського літака', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 106, 'en' => 'Private Jet', 'uk' => 'Приватний бізнес-джет', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 107, 'en' => 'Cargo Plane', 'uk' => 'Вантажний літак', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 108, 'en' => 'Helicopter Landing Pad', 'uk' => 'Вертолітний майданчик', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 109, 'en' => 'Train Station', 'uk' => 'Залізничний вокзал', 'category' => 'transit', 'tier' => 'children'],
        ['id' => 110, 'en' => 'Subway Station', 'uk' => 'Станція метрополітену', 'category' => 'transit', 'tier' => 'children'],
        ['id' => 111, 'en' => 'Bullet Train', 'uk' => 'Швидкісний поїзд', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 112, 'en' => 'Steam Locomotive', 'uk' => 'Паровоз', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 113, 'en' => 'Underground Metro Car', 'uk' => 'Вагон метро', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 114, 'en' => 'Central Bus Terminal', 'uk' => 'Центральний автовокзал', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 115, 'en' => 'Tram Depot', 'uk' => 'Трамвайне депо', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 116, 'en' => 'Ferry Terminal', 'uk' => 'Поромний термінал', 'category' => 'transit', 'tier' => 'children'],
        ['id' => 117, 'en' => 'Cruise Ship', 'uk' => 'Круїзний лайнер', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 118, 'en' => 'Ocean Liner', 'uk' => 'Океанський лайнер', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 119, 'en' => 'Submarine', 'uk' => 'Підводний човен', 'category' => 'transit', 'tier' => 'adults'],
        ['id' => 120, 'en' => 'Cargo Freighter', 'uk' => 'Вантажний суховантаж', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 121, 'en' => 'Container Port', 'uk' => 'Контейнерний порт', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 122, 'en' => 'Yacht Club', 'uk' => 'Яхт-клуб', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 123, 'en' => 'Sailboat', 'uk' => 'Вітрильна яхта', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 124, 'en' => 'Speedboat', 'uk' => 'Швидкісний катер', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 125, 'en' => 'Tugboat', 'uk' => 'Портовий буксир', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 126, 'en' => 'Fishing Trawler', 'uk' => 'Рибальський траулер', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 127, 'en' => 'Hovercraft', 'uk' => 'Судно на повітряній подушці', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 128, 'en' => 'Cable Car', 'uk' => 'Канатна дорога', 'category' => 'transit', 'tier' => 'children'],
        ['id' => 129, 'en' => 'Gondola Lift', 'uk' => 'Гондольний підйомник', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 130, 'en' => 'Monorail Station', 'uk' => 'Станція монорейки', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 131, 'en' => 'Zeppelin Airship', 'uk' => 'Дирижабль', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 132, 'en' => 'Hot Air Balloon', 'uk' => 'Повітряна куля', 'category' => 'transit', 'tier' => 'children'],
        ['id' => 133, 'en' => 'Space Station', 'uk' => 'Космічна орбітальна станція', 'category' => 'transit', 'tier' => 'adults'],
        ['id' => 134, 'en' => 'Spaceport', 'uk' => 'Космодром', 'category' => 'transit', 'tier' => 'adults'],
        ['id' => 135, 'en' => 'Rocket Launchpad', 'uk' => 'Стартовий комплекс ракети', 'category' => 'transit', 'tier' => 'adults'],
        ['id' => 136, 'en' => 'Lunar Base', 'uk' => 'Місячна дослідницька база', 'category' => 'transit', 'tier' => 'adults'],
        ['id' => 137, 'en' => 'Mars Habitat', 'uk' => 'Марсіанська колонія', 'category' => 'transit', 'tier' => 'adults'],
        ['id' => 138, 'en' => 'Orbital Satellite', 'uk' => 'Орбітальний супутник', 'category' => 'transit', 'tier' => 'adults'],
        ['id' => 139, 'en' => 'Taxi Stand', 'uk' => 'Стоянка таксі', 'category' => 'transit', 'tier' => 'children'],
        ['id' => 140, 'en' => 'Highway Toll Plaza', 'uk' => 'Пункт оплати автостради', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 141, 'en' => 'Mountain Pass Checkpoint', 'uk' => 'Блокпост на перевалі', 'category' => 'transit', 'tier' => 'adults'],
        ['id' => 142, 'en' => 'Border Crossing', 'uk' => 'Прикордонний перехід', 'category' => 'transit', 'tier' => 'adults'],
        ['id' => 143, 'en' => 'Canal Lock', 'uk' => 'Шлюз судноплавного каналу', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 144, 'en' => 'Shipyard Drydock', 'uk' => 'Судноремонтний док', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 145, 'en' => 'Submarine Pen', 'uk' => 'Бункер для підводних човнів', 'category' => 'transit', 'tier' => 'adults'],
        ['id' => 146, 'en' => 'Seaplane Base', 'uk' => 'База гідролітаків', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 147, 'en' => 'Bicycle Velodrome', 'uk' => 'Велодром', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 148, 'en' => 'Vintage Car Garage', 'uk' => 'Гараж раритетних авто', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 149, 'en' => 'Bus Stop', 'uk' => 'Автобусна зупинка', 'category' => 'transit', 'tier' => 'children'],
        ['id' => 150, 'en' => 'Funicular Railway', 'uk' => 'Фунікулер', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 151, 'en' => 'Suspension Bridge', 'uk' => 'Підвісний міст', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 152, 'en' => 'Undersea Tunnel', 'uk' => 'Підводний тунель', 'category' => 'transit', 'tier' => 'teens'],
        ['id' => 153, 'en' => 'Luxury Hotel', 'uk' => 'П\'ятизірковий готель', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 154, 'en' => 'Boutique Motel', 'uk' => 'Бутик-мотель', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 155, 'en' => 'Youth Hostel', 'uk' => 'Молодіжний хостел', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 156, 'en' => 'Mountain Ski Lodge', 'uk' => 'Гірськолижне шале', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 157, 'en' => 'Beach Resort', 'uk' => 'Пляжний курортний готель', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 158, 'en' => 'Safari Lodge', 'uk' => 'Сафарі-лодж', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 159, 'en' => 'Bed and Breakfast', 'uk' => 'Затишний гостьовий дім', 'category' => 'hospitality', 'tier' => 'children'],
        ['id' => 160, 'en' => 'Five-Star Restaurant', 'uk' => 'Елітний ресторан', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 161, 'en' => 'Fast Food Diner', 'uk' => 'Закусочна фастфуду', 'category' => 'hospitality', 'tier' => 'children'],
        ['id' => 162, 'en' => 'Pizzeria', 'uk' => 'Піцерія', 'category' => 'hospitality', 'tier' => 'children'],
        ['id' => 163, 'en' => 'French Bistro', 'uk' => 'Французьке бістро', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 164, 'en' => 'Sushi Bar', 'uk' => 'Суші-бар', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 165, 'en' => 'Tapas Restaurant', 'uk' => 'Тапас-бар', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 166, 'en' => 'Steakhouse', 'uk' => 'Стейк-хаус', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 167, 'en' => 'Dim Sum Parlor', 'uk' => 'Дімсам-ресторан', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 168, 'en' => 'Rooftop Lounge', 'uk' => 'Лаунж-бар на даху', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 169, 'en' => 'Coffee Shop', 'uk' => 'Кав\'ярня', 'category' => 'hospitality', 'tier' => 'children'],
        ['id' => 170, 'en' => 'Espresso Bar', 'uk' => 'Еспресо-бар', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 171, 'en' => 'Artisan Bakery', 'uk' => 'Крафтова пекарня', 'category' => 'hospitality', 'tier' => 'children'],
        ['id' => 172, 'en' => 'Pastry Shop', 'uk' => 'Кондитерська', 'category' => 'hospitality', 'tier' => 'children'],
        ['id' => 173, 'en' => 'Tea House', 'uk' => 'Чайний дім', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 174, 'en' => 'Speakeasy', 'uk' => 'Таємний підпільний бар (Спікізі)', 'category' => 'hospitality', 'tier' => 'adults'],
        ['id' => 175, 'en' => 'Traditional Pub', 'uk' => 'Традиційний паб', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 176, 'en' => 'Irish Tavern', 'uk' => 'Ірландська таверна', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 177, 'en' => 'Wine Cellar', 'uk' => 'Винний льох', 'category' => 'hospitality', 'tier' => 'adults'],
        ['id' => 178, 'en' => 'Vineyard Tasting Room', 'uk' => 'Дегустаційна зала виноробні', 'category' => 'hospitality', 'tier' => 'adults'],
        ['id' => 179, 'en' => 'Craft Brewery', 'uk' => 'Крафтова броварня', 'category' => 'hospitality', 'tier' => 'adults'],
        ['id' => 180, 'en' => 'Whiskey Distillery', 'uk' => 'Віскікурня', 'category' => 'hospitality', 'tier' => 'adults'],
        ['id' => 181, 'en' => 'Microbrewery', 'uk' => 'Мікропивоварня', 'category' => 'hospitality', 'tier' => 'adults'],
        ['id' => 182, 'en' => 'Cocktail Lounge', 'uk' => 'Коктейль-лаунж', 'category' => 'hospitality', 'tier' => 'adults'],
        ['id' => 183, 'en' => 'Nightclub', 'uk' => 'Нічний клуб', 'category' => 'hospitality', 'tier' => 'adults'],
        ['id' => 184, 'en' => 'Disco', 'uk' => 'Дискотека', 'category' => 'hospitality', 'tier' => 'adults'],
        ['id' => 185, 'en' => 'Karaoke Bar', 'uk' => 'Караоке-бар', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 186, 'en' => 'Jazz Club', 'uk' => 'Джаз-клуб', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 187, 'en' => 'Comedy Club', 'uk' => 'Стендап-клуб', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 188, 'en' => 'Hookah Lounge', 'uk' => 'Кальян-бар', 'category' => 'hospitality', 'tier' => 'adults'],
        ['id' => 189, 'en' => 'Catering Banquet Hall', 'uk' => 'Банкетна зала', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 190, 'en' => 'Buffet Restaurant', 'uk' => 'Ресторан шведського столу', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 191, 'en' => 'Food Truck Court', 'uk' => 'Майданчик фудтраків', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 192, 'en' => 'Drive-In Diner', 'uk' => 'Автокафе', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 193, 'en' => 'Ice Cream Parlor', 'uk' => 'Кафе-морозиво', 'category' => 'hospitality', 'tier' => 'children'],
        ['id' => 194, 'en' => 'Gelato Stand', 'uk' => 'Кіоск джелато', 'category' => 'hospitality', 'tier' => 'children'],
        ['id' => 195, 'en' => 'Juice Bar', 'uk' => 'Фреш-бар', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 196, 'en' => 'Deli and Sandwich Shop', 'uk' => 'Сендвіч-бар', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 197, 'en' => 'Chocolatier', 'uk' => 'Шоколадний бутик', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 198, 'en' => 'Fondue Chalet', 'uk' => 'Шале фондю', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 199, 'en' => 'Tiki Bar', 'uk' => 'Тікі-бар', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 200, 'en' => 'Hotel Penthouse Suite', 'uk' => 'Пентхаус готелю', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 201, 'en' => 'Hotel Lobby', 'uk' => 'Вестибюль готелю', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 202, 'en' => 'Hotel Kitchen', 'uk' => 'Ресторанна кухня готелю', 'category' => 'hospitality', 'tier' => 'teens'],
        ['id' => 203, 'en' => 'Broadway Theater', 'uk' => 'Бродвейський театр', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 204, 'en' => 'Opera House', 'uk' => 'Оперний театр', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 205, 'en' => 'Concert Hall', 'uk' => 'Концертна філармонія', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 206, 'en' => 'Movie Cinema', 'uk' => 'Кінотеатр', 'category' => 'entertainment', 'tier' => 'children'],
        ['id' => 207, 'en' => 'Drive-in Movie Theater', 'uk' => 'Автокінотеатр', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 208, 'en' => 'IMAX Dome', 'uk' => 'Купольний кінотеатр IMAX', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 209, 'en' => 'Recording Studio', 'uk' => 'Студія звукозапису', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 210, 'en' => 'Film Studio Backlot', 'uk' => 'Знімальний майданчик студії', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 211, 'en' => 'Television Broadcast Studio', 'uk' => 'Телевізійна студія', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 212, 'en' => 'Radio Station', 'uk' => 'Радіостанція', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 213, 'en' => 'Carnival Fairgrounds', 'uk' => 'Карнавальний ярмарок', 'category' => 'entertainment', 'tier' => 'children'],
        ['id' => 214, 'en' => 'Circus Big Top', 'uk' => 'Циркове шатро', 'category' => 'entertainment', 'tier' => 'children'],
        ['id' => 215, 'en' => 'Amusement Park', 'uk' => 'Парк атракціонів', 'category' => 'entertainment', 'tier' => 'children'],
        ['id' => 216, 'en' => 'Water Park', 'uk' => 'Аквапарк', 'category' => 'entertainment', 'tier' => 'children'],
        ['id' => 217, 'en' => 'Ferris Wheel', 'uk' => 'Оглядове колесо', 'category' => 'entertainment', 'tier' => 'children'],
        ['id' => 218, 'en' => 'Roller Coaster Station', 'uk' => 'Станція американських гірок', 'category' => 'entertainment', 'tier' => 'children'],
        ['id' => 219, 'en' => 'Haunted House', 'uk' => 'Будинок жахів', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 220, 'en' => 'Mirror Maze', 'uk' => 'Дзеркальний лабіринт', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 221, 'en' => 'Casino Gaming Floor', 'uk' => 'Ігрова зала казино', 'category' => 'entertainment', 'tier' => 'adults'],
        ['id' => 222, 'en' => 'VIP Poker Room', 'uk' => 'VIP покерна кімната', 'category' => 'entertainment', 'tier' => 'adults'],
        ['id' => 223, 'en' => 'Bingo Hall', 'uk' => 'Зала для бінго', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 224, 'en' => 'Arcade', 'uk' => 'Зала ігрових автоматів', 'category' => 'entertainment', 'tier' => 'children'],
        ['id' => 225, 'en' => 'VR Gaming Arena', 'uk' => 'VR арена віртуальної реальності', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 226, 'en' => 'Escape Room', 'uk' => 'Квест-кімната', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 227, 'en' => 'Bowling Alley', 'uk' => 'Боулінг-клуб', 'category' => 'entertainment', 'tier' => 'children'],
        ['id' => 228, 'en' => 'Billiards Hall', 'uk' => 'Більярдна зала', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 229, 'en' => 'Dart Pub', 'uk' => 'Дартс-клуб', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 230, 'en' => 'Laser Tag Arena', 'uk' => 'Лазертаг-арена', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 231, 'en' => 'Paintball Field', 'uk' => 'Пейнтбольне поле', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 232, 'en' => 'Mini Golf Course', 'uk' => 'Поле для мінігольфу', 'category' => 'entertainment', 'tier' => 'children'],
        ['id' => 233, 'en' => 'Go-Kart Track', 'uk' => 'Картинг-трек', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 234, 'en' => 'Skate Park', 'uk' => 'Скейт-парк', 'category' => 'entertainment', 'tier' => 'children'],
        ['id' => 235, 'en' => 'Ice Skating Rink', 'uk' => 'Ковзанка', 'category' => 'entertainment', 'tier' => 'children'],
        ['id' => 236, 'en' => 'Roller Skating Rink', 'uk' => 'Ролердром', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 237, 'en' => 'Wax Museum', 'uk' => 'Музей воскових фігур', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 238, 'en' => 'Puppet Theater', 'uk' => 'Ляльковий театр', 'category' => 'entertainment', 'tier' => 'children'],
        ['id' => 239, 'en' => 'Renaissance Fair', 'uk' => 'Ренесансний фестиваль', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 240, 'en' => 'Rodeo Arena', 'uk' => 'Родео-арена', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 241, 'en' => 'Music Festival Stage', 'uk' => 'Сцена музичного фестивалю', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 242, 'en' => 'Outdoor Amphitheater', 'uk' => 'Літній амфітеатр', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 243, 'en' => 'Sculpture Park', 'uk' => 'Парк скульптур', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 244, 'en' => 'Convention Exhibition Hall', 'uk' => 'Конгрес-хол виставок', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 245, 'en' => 'Trade Show Booth', 'uk' => 'Стенд торговельної виставки', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 246, 'en' => 'Costume Ball', 'uk' => 'Костюмований бал-маскарад', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 247, 'en' => 'Fashion Runway', 'uk' => 'Модний подіум', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 248, 'en' => 'Magic Show Club', 'uk' => 'Театр фокусів та ілюзій', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 249, 'en' => 'Planetarium Dome', 'uk' => 'Купол планетарію', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 250, 'en' => 'Art Auction House', 'uk' => 'Художній аукціонний дім', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 251, 'en' => 'Record Store', 'uk' => 'Крамниця вінілових платівок', 'category' => 'entertainment', 'tier' => 'teens'],
        ['id' => 252, 'en' => 'Comic Book Shop', 'uk' => 'Магазин коміксів', 'category' => 'entertainment', 'tier' => 'children'],
        ['id' => 253, 'en' => 'Football Stadium', 'uk' => 'Футбольний стадіон', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 254, 'en' => 'Soccer Arena', 'uk' => 'Футбольна арена', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 255, 'en' => 'Baseball Diamond', 'uk' => 'Бейсбольне поле', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 256, 'en' => 'Basketball Court', 'uk' => 'Баскетбольний майданчик', 'category' => 'sports', 'tier' => 'children'],
        ['id' => 257, 'en' => 'Tennis Center', 'uk' => 'Тенісний центр', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 258, 'en' => 'Wimbledon Court', 'uk' => 'Корт Вімблдону', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 259, 'en' => 'Olympic Swimming Pool', 'uk' => 'Олімпійський басейн', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 260, 'en' => 'Diving Tower', 'uk' => 'Вишка для стрибків у воду', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 261, 'en' => 'Boxing Gym', 'uk' => 'Боксерський зал', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 262, 'en' => 'Martial Arts Dojo', 'uk' => 'Додзьо бойових мистецтв', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 263, 'en' => 'Fencing Salle', 'uk' => 'Фехтувальний зал', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 264, 'en' => 'Gymnasium', 'uk' => 'Спортивна гімнастична зала', 'category' => 'sports', 'tier' => 'children'],
        ['id' => 265, 'en' => 'Crossfit Box', 'uk' => 'Кросфіт-зал', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 266, 'en' => 'Yoga Studio', 'uk' => 'Студія йоги', 'category' => 'sports', 'tier' => 'children'],
        ['id' => 267, 'en' => 'Pilates Center', 'uk' => 'Центр пілатесу', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 268, 'en' => 'Climbing Gym', 'uk' => 'Скеледром', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 269, 'en' => 'Bouldering Cave', 'uk' => 'Боулдеринг-зал', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 270, 'en' => 'Golf Course Clubhouse', 'uk' => 'Будинок гольф-клубу', 'category' => 'sports', 'tier' => 'children'],
        ['id' => 271, 'en' => 'Driving Range', 'uk' => 'Тренувальне поле для гольфу', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 272, 'en' => 'Horse Racing Track', 'uk' => 'Іподром', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 273, 'en' => 'Equestrian Stables', 'uk' => 'Кінноспортивні стайні', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 274, 'en' => 'Formula 1 Pit Lane', 'uk' => 'Піт-лейн Формули-1', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 275, 'en' => 'Drag Racing Strip', 'uk' => 'Траса для драг-рейсингу', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 276, 'en' => 'Ski Jump Ramp', 'uk' => 'Лижний трамплін', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 277, 'en' => 'Bobsled Run', 'uk' => 'Бобслейна траса', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 278, 'en' => 'Curling Rink', 'uk' => 'Керлінг-арена', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 279, 'en' => 'Surfing Beach', 'uk' => 'Серфінг-пляж', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 280, 'en' => 'Scuba Diving Reef', 'uk' => 'Риф для дайвінгу', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 281, 'en' => 'Rowing Boathouse', 'uk' => 'Елінг академічного веслування', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 282, 'en' => 'Whitewater Rafting River', 'uk' => 'Річка для рафтингу', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 283, 'en' => 'Skateboard Park', 'uk' => 'Скейтборд-парк', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 284, 'en' => 'BMX Track', 'uk' => 'Велотрек для BMX', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 285, 'en' => 'Shooting Range', 'uk' => 'Стрілецький тир', 'category' => 'sports', 'tier' => 'adults'],
        ['id' => 286, 'en' => 'Archery Field', 'uk' => 'Поле для стрільби з лука', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 287, 'en' => 'Wrestling Ring', 'uk' => 'Борцівський ринг', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 288, 'en' => 'Sumo Stable', 'uk' => 'Хея (школа сумо)', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 289, 'en' => 'Cricket Ground', 'uk' => 'Крикетне поле', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 290, 'en' => 'Rugby Pitch', 'uk' => 'Поле для регбі', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 291, 'en' => 'Polo Grounds', 'uk' => 'Поле для поло', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 292, 'en' => 'Ice Hockey Rink', 'uk' => 'Хокейна арена', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 293, 'en' => 'Locker Room', 'uk' => 'Спортивна роздягальня', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 294, 'en' => 'Sports Medicine Clinic', 'uk' => 'Клініка спортивної медицини', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 295, 'en' => 'Weightlifting Room', 'uk' => 'Зал важкої атлетики', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 296, 'en' => 'Athletic Track', 'uk' => 'Легкоатлетичний трек', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 297, 'en' => 'Marathon Finish Line', 'uk' => 'Фінішна брама марафону', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 298, 'en' => 'Mountain Bike Trailhead', 'uk' => 'Старт гірського веломаршруту', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 299, 'en' => 'Paragliding Launch Site', 'uk' => 'Майданчик зльоту парапланів', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 300, 'en' => 'Skydiving Dropzone', 'uk' => 'Зона десантування парашутистів', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 301, 'en' => 'Squash Court', 'uk' => 'Корт для сквошу', 'category' => 'sports', 'tier' => 'teens'],
        ['id' => 302, 'en' => 'Badminton Hall', 'uk' => 'Зал для бадмінтону', 'category' => 'sports', 'tier' => 'children'],
        ['id' => 303, 'en' => 'Shopping Mall', 'uk' => 'Торговий центр', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 304, 'en' => 'Department Store', 'uk' => 'Універмаг', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 305, 'en' => 'Supermarket', 'uk' => 'Супермаркет', 'category' => 'commercial', 'tier' => 'children'],
        ['id' => 306, 'en' => 'Farmer\'s Market', 'uk' => 'Фермерський ринок', 'category' => 'commercial', 'tier' => 'children'],
        ['id' => 307, 'en' => 'Fish Market', 'uk' => 'Рибний ринок', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 308, 'en' => 'Flower Market', 'uk' => 'Квітковий ринок', 'category' => 'commercial', 'tier' => 'children'],
        ['id' => 309, 'en' => 'Flea Market', 'uk' => 'Блошиний ринок', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 310, 'en' => 'Bazaar', 'uk' => 'Східний базар', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 311, 'en' => 'Souk', 'uk' => 'Традиційний східний сук', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 312, 'en' => 'Jewelry Boutique', 'uk' => 'Ювелірний бутик', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 313, 'en' => 'Luxury Watchmaker', 'uk' => 'Салон елітних годинників', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 314, 'en' => 'Antique Shop', 'uk' => 'Антикварна крамниця', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 315, 'en' => 'Pawn Shop', 'uk' => 'Ломбард', 'category' => 'commercial', 'tier' => 'adults'],
        ['id' => 316, 'en' => 'Tailor Shop', 'uk' => 'Ательє кравця', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 317, 'en' => 'Shoemaker Workshop', 'uk' => 'Майстерня шевця', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 318, 'en' => 'Bookstore', 'uk' => 'Книгарня', 'category' => 'commercial', 'tier' => 'children'],
        ['id' => 319, 'en' => 'Used Bookstore', 'uk' => 'Букіністична крамниця', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 320, 'en' => 'Toy Store', 'uk' => 'Магазин іграшок', 'category' => 'commercial', 'tier' => 'children'],
        ['id' => 321, 'en' => 'Pet Store', 'uk' => 'Зоомагазин', 'category' => 'commercial', 'tier' => 'children'],
        ['id' => 322, 'en' => 'Garden Nursery', 'uk' => 'Садовий розсадник', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 323, 'en' => 'Hardware Store', 'uk' => 'Будівельно-господарський магазин', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 324, 'en' => 'Lumber Yard', 'uk' => 'Склад лісоматеріалів', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 325, 'en' => 'Auto Dealership', 'uk' => 'Автосалон дилера', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 326, 'en' => 'Car Showroom', 'uk' => 'Виставковий автомобільний салон', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 327, 'en' => 'Gas Station Convenience Store', 'uk' => 'Мінімаркет на автозаправці', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 328, 'en' => 'Pharmacy', 'uk' => 'Аптека', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 329, 'en' => 'Apothecary', 'uk' => 'Старовинна аптека-травник', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 330, 'en' => 'Barber Shop', 'uk' => 'Барбершоп', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 331, 'en' => 'Beauty Salon', 'uk' => 'Салон краси', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 332, 'en' => 'Tattoo Parlor', 'uk' => 'Тату-салон', 'category' => 'commercial', 'tier' => 'adults'],
        ['id' => 333, 'en' => 'Dry Cleaner', 'uk' => 'Хімчистка', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 334, 'en' => 'Laundromat', 'uk' => 'Пральня самообслуговування', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 335, 'en' => 'Locksmith Shop', 'uk' => 'Майстерня з виготовлення ключів', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 336, 'en' => 'Photography Studio', 'uk' => 'Фотостудія', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 337, 'en' => 'Camera Store', 'uk' => 'Магазин професійної фототехніки', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 338, 'en' => 'Electronics Megastore', 'uk' => 'Гіпермаркет електроніки', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 339, 'en' => 'Furniture Showroom', 'uk' => 'Салон меблів та інтер\'єру', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 340, 'en' => 'Shoe Store', 'uk' => 'Магазин взуття', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 341, 'en' => 'Candy Shop', 'uk' => 'Магазин солодощів', 'category' => 'commercial', 'tier' => 'children'],
        ['id' => 342, 'en' => 'Tobacco Tobacconist', 'uk' => 'Тютюнова крамниця', 'category' => 'commercial', 'tier' => 'adults'],
        ['id' => 343, 'en' => 'Musical Instrument Store', 'uk' => 'Магазин музичних інструментів', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 344, 'en' => 'Fabric Outlet', 'uk' => 'Магазин тканин і текстилю', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 345, 'en' => 'Luggage Store', 'uk' => 'Магазин валіз та дорожніх сумок', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 346, 'en' => 'Eyewear Optician', 'uk' => 'Салон оптики', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 347, 'en' => 'Cosmetics Boutique', 'uk' => 'Бутик косметики та парфумерії', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 348, 'en' => 'Warehouse Club', 'uk' => 'Оптовий клуб-склад', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 349, 'en' => 'Wholesale Market', 'uk' => 'Оптовий ринок', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 350, 'en' => 'Flea Market Stall', 'uk' => 'Ятка на блошиному ринку', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 351, 'en' => 'Vending Machine Alley', 'uk' => 'Алея автоматів самообслуговування', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 352, 'en' => 'Ferry Duty Free Shop', 'uk' => 'Магазин безмитної торгівлі Duty Free', 'category' => 'commercial', 'tier' => 'teens'],
        ['id' => 353, 'en' => 'Automobile Assembly Plant', 'uk' => 'Автомобільний завод', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 354, 'en' => 'Steel Mill', 'uk' => 'Металургійний комбінат', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 355, 'en' => 'Oil Refinery', 'uk' => 'Нафтопереробний завод', 'category' => 'industry', 'tier' => 'adults'],
        ['id' => 356, 'en' => 'Offshore Oil Rig', 'uk' => 'Морська бурова платформа', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 357, 'en' => 'Hydroelectric Dam', 'uk' => 'Гідроелектростанція (ГЕС)', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 358, 'en' => 'Nuclear Power Station', 'uk' => 'Атомна електростанція (АЕС)', 'category' => 'industry', 'tier' => 'adults'],
        ['id' => 359, 'en' => 'Wind Turbine Farm', 'uk' => 'Вітрова електростанція', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 360, 'en' => 'Solar Panel Array', 'uk' => 'Сонячна електростанція', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 361, 'en' => 'Coal Mine', 'uk' => 'Вугільна шахта', 'category' => 'industry', 'tier' => 'adults'],
        ['id' => 362, 'en' => 'Gold Mine', 'uk' => 'Золотий рудник', 'category' => 'industry', 'tier' => 'adults'],
        ['id' => 363, 'en' => 'Diamond Mine', 'uk' => 'Алмазна копальня', 'category' => 'industry', 'tier' => 'adults'],
        ['id' => 364, 'en' => 'Quarry', 'uk' => 'Кам\'яний кар\'єр', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 365, 'en' => 'Logging Camp', 'uk' => 'Табір лісозаготівельників', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 366, 'en' => 'Sawmill', 'uk' => 'Лісопильня', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 367, 'en' => 'Chemical Factory', 'uk' => 'Хімічний завод', 'category' => 'industry', 'tier' => 'adults'],
        ['id' => 368, 'en' => 'Textile Mill', 'uk' => 'Текстильна фабрика', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 369, 'en' => 'Food Packaging Plant', 'uk' => 'Завод фасування продуктів', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 370, 'en' => 'Brewery Factory', 'uk' => 'Промисловий пивоварний завод', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 371, 'en' => 'Bottling Plant', 'uk' => 'Завод розливу напоїв', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 372, 'en' => 'Printing Press Facility', 'uk' => 'Поліграфічний комбінат', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 373, 'en' => 'Electronics Cleanroom', 'uk' => 'Стерильна лабораторія чипів', 'category' => 'industry', 'tier' => 'adults'],
        ['id' => 374, 'en' => 'Robotics Assembly Line', 'uk' => 'Роботизована складальна лінія', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 375, 'en' => 'Aircraft Hangar', 'uk' => 'Літаковий ангар', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 376, 'en' => 'Train Maintenance Depot', 'uk' => 'Локомотивне ремонтне депо', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 377, 'en' => 'Cargo Warehouse', 'uk' => 'Вантажний термінал-склад', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 378, 'en' => 'Cold Storage Freezer', 'uk' => 'Промисловий холодильний склад', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 379, 'en' => 'Shipping Container Yard', 'uk' => 'Майданчик морських контейнерів', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 380, 'en' => 'Water Treatment Plant', 'uk' => 'Водоочисна станція', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 381, 'en' => 'Desalination Facility', 'uk' => 'Опріснювальний комплекс', 'category' => 'industry', 'tier' => 'adults'],
        ['id' => 382, 'en' => 'Sewage Treatment Facility', 'uk' => 'Станція очищення стічних вод', 'category' => 'industry', 'tier' => 'adults'],
        ['id' => 383, 'en' => 'Recycling Facility', 'uk' => 'Сміттєпереробний комплекс', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 384, 'en' => 'Scrap Metal Junkyard', 'uk' => 'Пункт переробки металобрухту', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 385, 'en' => 'Landfill Site', 'uk' => 'Полігон утилізації відходів', 'category' => 'industry', 'tier' => 'adults'],
        ['id' => 386, 'en' => 'Power Substation', 'uk' => 'Трансформаторна підстанція', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 387, 'en' => 'Data Center Server Room', 'uk' => 'Серверний зал дата-центру', 'category' => 'industry', 'tier' => 'adults'],
        ['id' => 388, 'en' => 'Telecommunications Tower', 'uk' => 'Телекомунікаційна вежа', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 389, 'en' => 'Underground Utility Tunnel', 'uk' => 'Підземний інженерний колектор', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 390, 'en' => 'Electrical Switchyard', 'uk' => 'Розподільчий пункт енергомережі', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 391, 'en' => 'Pumping Station', 'uk' => 'Магістральна насосна станція', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 392, 'en' => 'Grain Elevator', 'uk' => 'Зерновий елеватор', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 393, 'en' => 'Cotton Gin', 'uk' => 'Бавовноочисна фабрика', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 394, 'en' => 'Cement Plant', 'uk' => 'Цементний завод', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 395, 'en' => 'Brick Kiln', 'uk' => 'Цегельний завод з печами', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 396, 'en' => 'Paper Mill', 'uk' => 'Паперово-целюлозний комбінат', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 397, 'en' => 'Glass Blowing Studio', 'uk' => 'Склодувна майстерня', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 398, 'en' => 'Blacksmith Forge', 'uk' => 'Ковальська кузня', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 399, 'en' => 'Foundry', 'uk' => 'Ливарний завод', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 400, 'en' => 'Shipbuilding Yard', 'uk' => 'Суднобудівна верф', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 401, 'en' => 'Dry Clean Industrial Plant', 'uk' => 'Промислова хімчистка', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 402, 'en' => 'Tire Factory', 'uk' => 'Шинний завод', 'category' => 'industry', 'tier' => 'teens'],
        ['id' => 403, 'en' => 'General Hospital', 'uk' => 'Міська багатопрофільна лікарня', 'category' => 'medical', 'tier' => 'teens'],
        ['id' => 404, 'en' => 'Emergency Room', 'uk' => 'Відділення невідкладної допомоги', 'category' => 'medical', 'tier' => 'teens'],
        ['id' => 405, 'en' => 'Operating Theater', 'uk' => 'Хірургічний операційний блок', 'category' => 'medical', 'tier' => 'teens'],
        ['id' => 406, 'en' => 'Intensive Care Unit', 'uk' => 'Відділення реанімації та інтенсивної терапії', 'category' => 'medical', 'tier' => 'teens'],
        ['id' => 407, 'en' => 'Maternity Ward', 'uk' => 'Пологове відділення', 'category' => 'medical', 'tier' => 'teens'],
        ['id' => 408, 'en' => 'Pediatric Clinic', 'uk' => 'Дитяча поліклініка', 'category' => 'medical', 'tier' => 'children'],
        ['id' => 409, 'en' => 'Psychiatric Hospital', 'uk' => 'Психіатрична клініка', 'category' => 'medical', 'tier' => 'adults'],
        ['id' => 410, 'en' => 'Dental Surgery', 'uk' => 'Стоматологічна клініка', 'category' => 'medical', 'tier' => 'teens'],
        ['id' => 411, 'en' => 'Optometrist Clinic', 'uk' => 'Офтальмологічний кабінет', 'category' => 'medical', 'tier' => 'teens'],
        ['id' => 412, 'en' => 'Physical Therapy Center', 'uk' => 'Центр фізіотерапії та реабілітації', 'category' => 'medical', 'tier' => 'teens'],
        ['id' => 413, 'en' => 'Blood Donation Bank', 'uk' => 'Центр заготівлі донорської крові', 'category' => 'medical', 'tier' => 'teens'],
        ['id' => 414, 'en' => 'Medical Research Laboratory', 'uk' => 'Медична дослідна лабораторія', 'category' => 'medical', 'tier' => 'teens'],
        ['id' => 415, 'en' => 'Pathology Morgue', 'uk' => 'Патологоанатомічний морг', 'category' => 'medical', 'tier' => 'adults'],
        ['id' => 416, 'en' => 'Coroner Office', 'uk' => 'Бюро судово-медичної експертизи', 'category' => 'medical', 'tier' => 'adults'],
        ['id' => 417, 'en' => 'Forensics Crime Lab', 'uk' => 'Криміналістична лабораторія', 'category' => 'medical', 'tier' => 'adults'],
        ['id' => 418, 'en' => 'Ambulance Dispatch Bay', 'uk' => 'Диспетчерський бокс швидкої допомоги', 'category' => 'medical', 'tier' => 'teens'],
        ['id' => 419, 'en' => 'Fire Department Garage', 'uk' => 'Гараж пожежно-рятувальної служби', 'category' => 'medical', 'tier' => 'teens'],
        ['id' => 420, 'en' => 'Police Precinct', 'uk' => 'Поліцейське управління', 'category' => 'medical', 'tier' => 'teens'],
        ['id' => 421, 'en' => 'Holding Cell', 'uk' => 'Камера тимчасового тримання', 'category' => 'medical', 'tier' => 'adults'],
        ['id' => 422, 'en' => 'Interrogation Room', 'uk' => 'Кімната для допитів', 'category' => 'medical', 'tier' => 'adults'],
        ['id' => 423, 'en' => 'Lineup Room', 'uk' => 'Кімната впізнання підозрюваних', 'category' => 'medical', 'tier' => 'adults'],
        ['id' => 424, 'en' => 'County Jail', 'uk' => 'Окружна в\'язниця', 'category' => 'medical', 'tier' => 'adults'],
        ['id' => 425, 'en' => 'Maximum Security Prison', 'uk' => 'В\'язниця суворого режиму', 'category' => 'medical', 'tier' => 'adults'],
        ['id' => 426, 'en' => 'Prison Yard', 'uk' => 'Тюремне подвір\'я для прогулянок', 'category' => 'medical', 'tier' => 'adults'],
        ['id' => 427, 'en' => 'Prison Cafeteria', 'uk' => 'Тюремна їдальня', 'category' => 'medical', 'tier' => 'adults'],
        ['id' => 428, 'en' => 'Guard Tower', 'uk' => 'Вартова вежа периметра', 'category' => 'medical', 'tier' => 'adults'],
        ['id' => 429, 'en' => 'Quarantine Zone', 'uk' => 'Карантинна ізоляційна зона', 'category' => 'medical', 'tier' => 'adults'],
        ['id' => 430, 'en' => 'Epidemic Containment Ward', 'uk' => 'Бокс інфекційного захисту', 'category' => 'medical', 'tier' => 'adults'],
        ['id' => 431, 'en' => 'Biohazard Bio-Lab', 'uk' => 'Біолабораторія 4 рівня небезпеки', 'category' => 'medical', 'tier' => 'adults'],
        ['id' => 432, 'en' => 'Rehabilitation Center', 'uk' => 'Наркологічний реабілітаційний центр', 'category' => 'medical', 'tier' => 'teens'],
        ['id' => 433, 'en' => 'Nursing Home', 'uk' => 'Пансіонат для людей літнього віку', 'category' => 'medical', 'tier' => 'teens'],
        ['id' => 434, 'en' => 'Hospice Facility', 'uk' => 'Хоспіс паліативної допомоги', 'category' => 'medical', 'tier' => 'teens'],
        ['id' => 435, 'en' => 'Urgent Care Clinic', 'uk' => 'Клініка невідкладної допомоги', 'category' => 'medical', 'tier' => 'teens'],
        ['id' => 436, 'en' => 'Veterinary Hospital', 'uk' => 'Ветеринарна клініка', 'category' => 'medical', 'tier' => 'children'],
        ['id' => 437, 'en' => 'Animal Shelter', 'uk' => 'Притулок для тварин', 'category' => 'medical', 'tier' => 'children'],
        ['id' => 438, 'en' => 'Search and Rescue Station', 'uk' => 'Гірська пошуково-рятувальна станція', 'category' => 'medical', 'tier' => 'teens'],
        ['id' => 439, 'en' => 'Coast Guard Base', 'uk' => 'База берегової охорони', 'category' => 'medical', 'tier' => 'teens'],
        ['id' => 440, 'en' => 'Life Guard Tower', 'uk' => 'Спостережна вишка рятувальників', 'category' => 'medical', 'tier' => 'teens'],
        ['id' => 441, 'en' => 'Disaster Relief Center', 'uk' => 'Штаб ліквідації надзвичайних ситуацій', 'category' => 'medical', 'tier' => 'teens'],
        ['id' => 442, 'en' => 'Bomb Shelter', 'uk' => 'Укріплене бомбосховище', 'category' => 'medical', 'tier' => 'adults'],
        ['id' => 443, 'en' => 'Hazardous Waste Depot', 'uk' => 'Сховище токсичних відходів', 'category' => 'medical', 'tier' => 'adults'],
        ['id' => 444, 'en' => 'Fingerprint Identification Unit', 'uk' => 'Дактилоскопічний відділ', 'category' => 'medical', 'tier' => 'teens'],
        ['id' => 445, 'en' => 'Armored Cash Van Depot', 'uk' => 'База інкасаторських броньовиків', 'category' => 'medical', 'tier' => 'teens'],
        ['id' => 446, 'en' => 'Evidence Locker', 'uk' => 'Кімната речових доказів', 'category' => 'medical', 'tier' => 'teens'],
        ['id' => 447, 'en' => 'Courtroom Holding Cell', 'uk' => 'Конвойне приміщення суду', 'category' => 'medical', 'tier' => 'teens'],
        ['id' => 448, 'en' => 'Paramedic Helicopter Pad', 'uk' => 'Вертолітний майданчик санавіації', 'category' => 'medical', 'tier' => 'teens'],
        ['id' => 449, 'en' => 'Detox Center', 'uk' => 'Відділення детоксикації', 'category' => 'medical', 'tier' => 'adults'],
        ['id' => 450, 'en' => 'Orthopedic Ward', 'uk' => 'Травматолого-ортопедичне відділення', 'category' => 'medical', 'tier' => 'teens'],
        ['id' => 451, 'en' => 'Radiology CT-Scan Room', 'uk' => 'Кабінет КТ та МРТ томографії', 'category' => 'medical', 'tier' => 'teens'],
        ['id' => 452, 'en' => 'Pharmacy Dispensary', 'uk' => 'Аптечний склад лікарні', 'category' => 'medical', 'tier' => 'teens'],
        ['id' => 453, 'en' => 'Secret Underground Bunker', 'uk' => 'Секретний підземний бункер', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 454, 'en' => 'Spy Safehouse', 'uk' => 'Конспіративна квартира шпигуна', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 455, 'en' => 'Surveillance Van', 'uk' => 'Фургон прихованого спостереження', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 456, 'en' => 'Submarine Command Center', 'uk' => 'Командний пункт підводного човна', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 457, 'en' => 'Missile Silo Control Room', 'uk' => 'Бункер управління ядерною шахтою', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 458, 'en' => 'Radar Early Warning Station', 'uk' => 'Радарна станція раннього виявлення', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 459, 'en' => 'Military Command Bunker', 'uk' => 'Командний пункт генерального штабу', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 460, 'en' => 'Air Force Base', 'uk' => 'Військово-повітряна авіабаза', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 461, 'en' => 'Naval Dockyard', 'uk' => 'Військово-морська верф', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 462, 'en' => 'Army Barracks', 'uk' => 'Армійські казарми спецпризначенців', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 463, 'en' => 'Sniper Nest', 'uk' => 'Замасковане снайперське гніздо', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 464, 'en' => 'Checkpoint Alpha', 'uk' => 'Укріплений блокпост «Альфа»', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 465, 'en' => 'Demilitarized Zone', 'uk' => 'Демілітаризована прикордонна зона', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 466, 'en' => 'Trench Warfare Bunker', 'uk' => 'Окопний бліндаж лінії фронту', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 467, 'en' => 'Intelligence Agency Headquarters', 'uk' => 'Штаб-квартира зовнішньої розвідки', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 468, 'en' => 'Cipher and Cryptography Vault', 'uk' => 'Сховище шифрів та дешифрувальників', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 469, 'en' => 'Black Site Detention Facility', 'uk' => 'Секретний об\'єкт допитів (Black Site)', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 470, 'en' => 'Undercover Sting Apartment', 'uk' => 'Квартира оперативної розробки під прикриттям', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 471, 'en' => 'Counter-Terrorism Briefing Room', 'uk' => 'Ситуаційна зала антитерористичного центру', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 472, 'en' => 'Diplomatic Pouch Vault', 'uk' => 'Сховище дипломатичної пошти', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 473, 'en' => 'Antarctic Research Outpost', 'uk' => 'Антарктична полярна станція', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 474, 'en' => 'Deep Sea Exploration Pod', 'uk' => 'Глибоководний дослідницький батискаф', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 475, 'en' => 'Arctic Icebreaker Bridge', 'uk' => 'Капітанський місток арктичного криголама', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 476, 'en' => 'Desert Military Oasis', 'uk' => 'Військовий табір в оазисі пустелі', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 477, 'en' => 'Jungle Outpost', 'uk' => 'Замаскований пост у джунглях', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 478, 'en' => 'Mountain Lookout Tower', 'uk' => 'Гірська спостережна вишка', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 479, 'en' => 'Volcano Monitoring Station', 'uk' => 'Станція моніторингу активності вулкану', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 480, 'en' => 'Ghost Town Saloon', 'uk' => 'Салун у мертвому місті-привиді', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 481, 'en' => 'Abandoned Asylum', 'uk' => 'Покинута психіатрична лікарня', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 482, 'en' => 'Shipwreck Ocean Floor', 'uk' => 'Затонуле судно на дні океану', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 483, 'en' => 'Deep Underground Mine Shaft', 'uk' => 'Глибока шахта стратегічних копалин', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 484, 'en' => 'Alpine Chalet Hideout', 'uk' => 'Альпійське сховище в шале', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 485, 'en' => 'High Security Bank Vault', 'uk' => 'Банківське сховище вищої категорії захисту', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 486, 'en' => 'Private Island Villa', 'uk' => 'Укріплена вілла на приватному острові', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 487, 'en' => 'Remote Monorail Terminal', 'uk' => 'Глухий термінал гірської монорейки', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 488, 'en' => 'Secluded Monastery Cell', 'uk' => 'Таємна монастирська келія', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 489, 'en' => 'Underground Smuggler Tunnel', 'uk' => 'Підземний тунель контрабандистів', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 490, 'en' => 'Camouflaged Radar Dome', 'uk' => 'Замаскований радіолокаційний купол', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 491, 'en' => 'Border Patrol Lookout', 'uk' => 'Прихований спостережний пункт кордону', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 492, 'en' => 'Air Defense Battery', 'uk' => 'Позиція батареї ППО', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 493, 'en' => 'Drone Command Center', 'uk' => 'Центр управління ударними БПЛА', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 494, 'en' => 'Satellite Uplink Station', 'uk' => 'Станція супутникового спецзв\'язку', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 495, 'en' => 'Classified Archive Vault', 'uk' => 'Сховище секретних архівів спецслужб', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 496, 'en' => 'Nuclear Submarine Reactor Room', 'uk' => 'Реакторний відсік атомного підводного човна', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 497, 'en' => 'Presidential Emergency Operations Center', 'uk' => 'Президентський підземний бункер надзвичайних ситуацій', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 498, 'en' => 'War Room Table', 'uk' => 'Стіл ситуаційного командування (War Room)', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 499, 'en' => 'Embassy Roof Helipad', 'uk' => 'Вертолітний майданчик даху посольства', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 500, 'en' => 'Secret Tunnel Beneath Border', 'uk' => 'Таємний підкоп під державним кордоном', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 501, 'en' => 'Smuggler Speedboat Harbor', 'uk' => 'Прихована стоянка катерів контрабанди', 'category' => 'espionage', 'tier' => 'adults'],
        ['id' => 502, 'en' => 'High-Tech Covert Laboratory', 'uk' => 'Секретна наукова кіберлабораторія', 'category' => 'espionage', 'tier' => 'adults'],
    ];
}
