<?php

namespace App\Support;

/**
 * The Phrase game's pools: well-known sayings, proverbs and lines, one pool
 * per language. Ids are stored in phrase_rounds, so never renumber or
 * reorder: append new phrases with the next id. Every player needs a word
 * of their own, so a game draws only phrases at least as long as its table;
 * keep enough 10-word phrases for the largest (10-player) tables.
 */
class PhraseData
{
    /**
     * @var array<string, list<array{id: int, text: string}>>
     */
    public const PHRASES = [
        'en' => [
            ['id' => 1, 'text' => 'Actions speak louder than words'],
            ['id' => 2, 'text' => 'Better late than never'],
            ['id' => 3, 'text' => 'Practice makes perfect'],
            ['id' => 4, 'text' => 'Time is money'],
            ['id' => 5, 'text' => 'Knowledge is power'],
            ['id' => 6, 'text' => 'Every cloud has a silver lining'],
            ['id' => 7, 'text' => 'Don\'t judge a book by its cover'],
            ['id' => 8, 'text' => 'The early bird catches the worm'],
            ['id' => 9, 'text' => 'When in Rome, do as the Romans do'],
            ['id' => 10, 'text' => 'A picture is worth a thousand words'],
            ['id' => 11, 'text' => 'Rome wasn\'t built in a day'],
            ['id' => 12, 'text' => 'Where there\'s a will, there\'s a way'],
            ['id' => 13, 'text' => 'Don\'t count your chickens before they hatch'],
            ['id' => 14, 'text' => 'An apple a day keeps the doctor away'],
            ['id' => 15, 'text' => 'All that glitters is not gold'],
            ['id' => 16, 'text' => 'Two heads are better than one'],
            ['id' => 17, 'text' => 'Honesty is the best policy'],
            ['id' => 18, 'text' => 'Curiosity killed the cat'],
            ['id' => 19, 'text' => 'Don\'t put all your eggs in one basket'],
            ['id' => 20, 'text' => 'The pen is mightier than the sword'],
            ['id' => 21, 'text' => 'Birds of a feather flock together'],
            ['id' => 22, 'text' => 'A friend in need is a friend indeed'],
            ['id' => 23, 'text' => 'You can lead a horse to water, but you can\'t make it drink'],
            ['id' => 24, 'text' => 'Laughter is the best medicine'],
            ['id' => 25, 'text' => 'Beauty is in the eye of the beholder'],
            ['id' => 26, 'text' => 'Necessity is the mother of invention'],
            ['id' => 27, 'text' => 'If it ain\'t broke, don\'t fix it'],
            ['id' => 28, 'text' => 'Absence makes the heart grow fonder'],
            ['id' => 29, 'text' => 'The grass is always greener on the other side of the fence'],
            ['id' => 30, 'text' => 'Look before you leap'],
            ['id' => 31, 'text' => 'Too many cooks spoil the broth'],
            ['id' => 32, 'text' => 'Great minds think alike'],
            ['id' => 33, 'text' => 'There\'s no place like home'],
            ['id' => 34, 'text' => 'Easy come, easy go'],
            ['id' => 35, 'text' => 'A watched pot never boils'],
            ['id' => 36, 'text' => 'Don\'t cry over spilled milk'],
            ['id' => 37, 'text' => 'Fortune favors the bold'],
            ['id' => 38, 'text' => 'Every dog has its day'],
            ['id' => 39, 'text' => 'Still waters run deep'],
            ['id' => 40, 'text' => 'It takes two to tango'],
            ['id' => 41, 'text' => 'Slow and steady wins the race'],
            ['id' => 42, 'text' => 'The best things in life are free'],
            ['id' => 43, 'text' => 'Out of sight, out of mind'],
            ['id' => 44, 'text' => 'Ignorance is bliss'],
            ['id' => 45, 'text' => 'A penny saved is a penny earned'],
            ['id' => 46, 'text' => 'Don\'t bite the hand that feeds you'],
            ['id' => 47, 'text' => 'When life gives you lemons, make lemonade'],
            ['id' => 48, 'text' => 'People who live in glass houses should not throw stones'],
            ['id' => 49, 'text' => 'A journey of a thousand miles begins with a single step'],
            ['id' => 50, 'text' => 'Give a man a fish and you feed him for a day'],
            ['id' => 51, 'text' => 'To be or not to be, that is the question'],
            ['id' => 52, 'text' => 'Ask not what your country can do for you'],
            ['id' => 53, 'text' => 'A bird in the hand is worth two in the bush'],
            ['id' => 54, 'text' => 'Don\'t look a gift horse in the mouth'],
            ['id' => 55, 'text' => 'The squeaky wheel gets the grease'],
            ['id' => 56, 'text' => 'You can\'t have your cake and eat it too'],
            ['id' => 57, 'text' => 'Keep your friends close and your enemies closer'],
            ['id' => 58, 'text' => 'Hope for the best, prepare for the worst'],
            ['id' => 59, 'text' => 'Do unto others as you would have them do unto you'],
            ['id' => 60, 'text' => 'The road to hell is paved with good intentions'],
            ['id' => 61, 'text' => 'Early to bed and early to rise makes a man healthy, wealthy, and wise'],
            ['id' => 62, 'text' => 'If at first you don\'t succeed, try, try again'],
            ['id' => 63, 'text' => 'One small step for man, one giant leap for mankind'],
            ['id' => 64, 'text' => 'Sticks and stones may break my bones, but words will never hurt me'],
        ],
        'uk' => [
            ['id' => 1, 'text' => 'Без труда нема плода'],
            ['id' => 2, 'text' => 'Вік живи, вік учись'],
            ['id' => 3, 'text' => 'Не кажи гоп, поки не перескочиш'],
            ['id' => 4, 'text' => 'Тихіше їдеш, далі будеш'],
            ['id' => 5, 'text' => 'Яблуко від яблуні недалеко падає'],
            ['id' => 6, 'text' => 'Друзі пізнаються в біді'],
            ['id' => 7, 'text' => 'Не плюй у криницю, бо доведеться води напитися'],
            ['id' => 8, 'text' => 'Що посієш, те й пожнеш'],
            ['id' => 9, 'text' => 'Краще синиця в жмені, ніж журавель у небі'],
            ['id' => 10, 'text' => 'Під лежачий камінь вода не тече'],
            ['id' => 11, 'text' => 'Сім разів відміряй, один раз відріж'],
            ['id' => 12, 'text' => 'Не все те золото, що блищить'],
            ['id' => 13, 'text' => 'Терпи, козаче, отаманом будеш'],
            ['id' => 14, 'text' => 'Козацькому роду нема переводу'],
            ['id' => 15, 'text' => 'В своїй хаті своя й правда, і сила, і воля'],
            ['id' => 16, 'text' => 'Борітеся, поборете, вам Бог помагає'],
            ['id' => 17, 'text' => 'Учітесь, брати мої, думайте, читайте, і чужому научайтесь, й свого не цурайтесь'],
            ['id' => 18, 'text' => 'Хто рано встає, тому Бог дає'],
            ['id' => 19, 'text' => 'Обіцянка-цяцянка, а дурневі радість'],
            ['id' => 20, 'text' => 'Апетит приходить під час їди'],
            ['id' => 21, 'text' => 'Слово не горобець, вилетить, не спіймаєш'],
            ['id' => 22, 'text' => 'Вовків боятися, в ліс не ходити'],
            ['id' => 23, 'text' => 'Не май сто рублів, а май сто друзів'],
            ['id' => 24, 'text' => 'На смак і колір товариша нема'],
            ['id' => 25, 'text' => 'Гуртом і батька легше бити'],
            ['id' => 26, 'text' => 'Як дбаєш, так і маєш'],
            ['id' => 27, 'text' => 'Ранок вечора мудріший'],
            ['id' => 28, 'text' => 'Не так сталося, як гадалося'],
            ['id' => 29, 'text' => 'Бачили очі, що купували'],
            ['id' => 30, 'text' => 'Риба шукає, де глибше, а людина, де краще'],
            ['id' => 31, 'text' => 'Згода будує, а незгода руйнує'],
            ['id' => 32, 'text' => 'Без верби і калини нема України'],
            ['id' => 33, 'text' => 'Вчення світ, а невчення тьма'],
            ['id' => 34, 'text' => 'Хто шукає, той знайде'],
            ['id' => 35, 'text' => 'Кінець ділу вінець'],
            ['id' => 36, 'text' => 'Не відкладай на завтра те, що можна зробити сьогодні'],
            ['id' => 37, 'text' => 'Скажи мені, хто твій друг, і я скажу, хто ти'],
            ['id' => 38, 'text' => 'Що маємо, не бережемо, втративши, плачемо'],
            ['id' => 39, 'text' => 'Нема лиха без добра'],
            ['id' => 40, 'text' => 'Діло майстра величає'],
            ['id' => 41, 'text' => 'Чужу біду руками розведу, а до своєї розуму не докладу'],
            ['id' => 42, 'text' => 'Щастя не в грошах'],
            ['id' => 43, 'text' => 'Не той друг, хто медом маже, а той, хто правду каже'],
            ['id' => 44, 'text' => 'Добре там, де нас нема'],
            ['id' => 45, 'text' => 'У чужому оці порошинку бачиш, а в своєму колоди не помічаєш'],
            ['id' => 46, 'text' => 'Хліб усьому голова'],
            ['id' => 47, 'text' => 'І вовки ситі, і кози цілі'],
            ['id' => 48, 'text' => 'Любиш кататися, люби й саночки возити'],
            ['id' => 49, 'text' => 'Хто на молоці опікся, той і на воду дме'],
            ['id' => 50, 'text' => 'Добрий початок, половина діла'],
            ['id' => 51, 'text' => 'Не народись багатим, а народись щасливим'],
            ['id' => 52, 'text' => 'Голод не тітка, пиріжка не дасть'],
            ['id' => 53, 'text' => 'Ой у лузі червона калина похилилася'],
            ['id' => 54, 'text' => 'Ще не вмерла України і слава, і воля'],
            ['id' => 55, 'text' => 'Як умру, то поховайте мене на могилі'],
            ['id' => 56, 'text' => 'Реве та стогне Дніпр широкий'],
            ['id' => 57, 'text' => 'Як ти до людей, так і люди до тебе'],
            ['id' => 58, 'text' => 'Чим багаті, тим і раді'],
            ['id' => 59, 'text' => 'Як аукнеться, так і відгукнеться'],
            ['id' => 60, 'text' => 'Не буди лихо, поки тихо'],
            ['id' => 61, 'text' => 'Любіть Україну, як сонце, любіть, як вітер, і трави, і води'],
            ['id' => 62, 'text' => 'Ніч яка місячна, зоряна, ясная'],
        ],
    ];
}
